<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-03-11 13:54

$extensionPath = t3lib_extMgm::extPath('plupload');
$extensionClassesPath = t3lib_extMgm::extPath('plupload') . 'Classes/';
return array(
	'tx_plupload_ajaxhandler' => $extensionClassesPath . 'AjaxHandler.php',
	'tx_plupload_abstracthook' => $extensionClassesPath . 'Hooks/AbstractHook.php',
	'tx_plupload_backendhook' => $extensionClassesPath . 'Hooks/BackendHook.php',
	'tx_plupload_clickmenuhook' => $extensionClassesPath . 'Hooks/ClickMenuHook.php',
	'tx_plupload_templatehook' => $extensionClassesPath . 'Hooks/TemplateHook.php',
);
?>